USE [QLPHONGKHAM]
GO
/****** Object:  StoredProcedure [dbo].[uspGetListMedicalHistory]    Script Date: 21/01/2024 09:26:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[uspGetListMedicalHistory]
			@maBN CHAR(15)
AS
BEGIN
	SELECT MABN, CONVERT(VARCHAR, NGAYDIEUTRI, 105) AS NGAYDIEUTRI, CHANDOAN, TRANGTHAITHANHTOAN, TONGCHIPHI
	FROM dbo.BENHSU
	WHERE MABN = @maBN
END