USE [QLPHONGKHAM]
GO
/****** Object:  StoredProcedure [dbo].[uspGetPatientDetailInformation]    Script Date: 21/01/2024 09:29:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[uspGetPatientDetailInformation]
		@maBN CHAR(15)
AS
BEGIN
	SELECT ID, MABN, HOTEN_BN, CONVERT(VARCHAR, NGAYSINH, 105) AS NGAYSINH, GIOITINH, SDT_BN, EMAIL_BN,
			DIACHI, CHONGCHIDINH, DIUNG
	FROM dbo.BENHNHAN
	WHERE MABN = @maBN
END