CREATE OR ALTER PROCEDURE [dbo].[uspGetListMedicalHistory]
			@maBN CHAR(15)
AS
BEGIN
	SELECT MABN, CONVERT(VARCHAR, NGAYDIEUTRI, 105) AS NGAYDIEUTRI, HOTEN_BS AS TENBACSI, CHANDOAN, TRIEUCHUNG, TRANGTHAITHANHTOAN, TONGCHIPHI
	FROM dbo.BENHSU BSU JOIN dbo.BACSI BS ON BSU.MABACSI = BS.MABACSI
	WHERE MABN = @maBN
END